{% set name = "sam2" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  noarch: generic
  number: 0

requirements:
  run:
    - sam-2 >=1

test:
  imports:
    - sam2
    - sam2_configs

about:
  home: https://github.com/facebookresearch/segment-anything-2
  summary: 'SAM 2: Segment Anything in Images and Videos'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
